### ISSUE TITLE
NLTK dependency

### ISSUE THREAD

**Issue by mbanon** [kumparan/nlp-id#16]
Hello,
I am using nlp-id, and I noticed that it requieres NLTK==3.8.1. Since that version has been reported as containing a vulnerability (https://github.com/advisories/GHSA-cgvx-9447-vcch), a new version (3.8.2) has been released.
Do you plan to update the nlp-id requirement as well, so it depends on the patched version?
Thanks!

**Comment by zavliju** [comment]
Thanks for the heads up. 
The nlp-id package will be updated with the latest NLTK version and published soon.

**Comment by mbanon** [comment]
Thanks @zavliju for the superfast response! :)

**Comment by mbanon** [comment]
Hi again @zavliju , apparently the NLTK people removed version 3.8.2 from pypi and now it should be 3.9+ (latest is 3.9.1), as per https://github.com/nltk/nltk/issues/3301

**Comment by zavliju** [comment]
Hi again @mbanon, 
We also already published nlp-id with latest NLTK(3.9.1)

You can find it here: https://pypi.org/project/nlp-id/0.1.18.0/

Thanks ^^

**Comment by mbanon** [comment]
Thanks! <3
